### ISSUE TITLE
Route merging leads to 502 error on `/api/main`

### ISSUE THREAD

**Issue by arctic-hen7** [vercel-community/rust#106]
Using the route merging feature, hits to API endpoints that don't exist return 404 errors, as expected, but hitting `/api/main`, at least when using `vercel dev`, leads to a 502 error when it doesn't exist, with the following console output:

```
thread 'main' panicked at 'internal error: entered unreachable code', api/api/main.rs:10:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>)
    at new LambdaError (/home/arctic-hen7/.nvm/versions/node/v19.3.0/lib/node_modules/vercel/dist/index.js:8983:16)                                  
    at Lambda.<anonymous> (/home/arctic-hen7/.nvm/versions/node/v19.3.0/lib/node_modules/vercel/dist/index.js:9116:27)                                  
    at Generator.next (<anonymous>)
    at fulfilled (/home/arctic-hen7/.nvm/versions/node/v19.3.0/lib/node_modules/vercel/dist/index.js:9030:58
```

For me, this can be replicated with a minimal route merging configuration as in the readme. Note that line 10 refers to the `#[bundled_api]` macro. Unfortunately running `RUST_BACKTRACE=1 vercel dev` doesn't seem to pass the environment variable through for me, so I'm not sure how exactly to get a backtrace on this error locally.

**Comment by manglemix** [comment]
I am still facing this issue in the exact same manner
