### ISSUE TITLE
Missing ENV variable process.env.HOME

### ISSUE THREAD

**Issue by CupertinoWasTaken** [vercel-community/rust#98]
I've been trying to use vercel-rust since a very long time, I'm currently using 4.0.0-beta.4 and I'm getting this error when i try to run the serverless function.

```
> Building vercel-rust@4.0.0-beta.4:api/search2.rs
Error: Missing ENV variable process.env.HOME
    at assertEnv (C:\Users\#\AppData\Local\com.vercel.cli\Cache\dev\builders\node_modules\vercel-rust\dist\lib\utils.js:26:15)
    at Object.<anonymous> (C:\Users\#\AppData\Local\com.vercel.cli\Cache\dev\builders\node_modules\vercel-rust\dist\index.js:31:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\#\AppData\Local\com.vercel.cli\Cache\dev\builders\node_modules\vercel-rust\dist\index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Zxilly** [comment]
I also met this error, I have write a patch to fix it.

**Comment by Zxilly** [comment]
![image](https://github.com/vercel-community/rust/assets/31370133/5bd153c8-aee3-40d2-8acb-c7ecf71d7f18)
Works as expected.
